AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9

Resources:
  FoodDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: .
      Environment:
        Variables:
          DYNAMODB_TABLE: FoodOrders
      Policies:
        - DynamoDBCrudPolicy:
            TableName: FoodOrders
        - CloudWatchLogsFullAccess

  FoodOrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FoodOrders
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"